### ISSUE TITLE
Link to the slides?

### ISSUE THREAD

**Issue by tomekwi** [substack/data-structures-of-the-revolution#1]
Hi, good stuff!

Looks like content of some slides from some talk. Do you have the talk recorded somewhere? Or the slides themselves? Can you share a link?

**Comment by substack** [comment]
readme.markdown is the slides. The `---` is the slide boundary token which you can view with [tslide](https://www.npmjs.com/package/tslide). I don't think this talk was recorded.

**Comment by tomekwi** [comment]
Great, thanks!
